Create "2021 Deview Chapter.1" post
makinarocks/makinarocks.github.io pull request #49
Opened 2021-11-17 07:22 UTC by jiyoonlim123

2021-11-18 02:36 UTC, Curt-Park commented
`_posts/2021-11-24-introduce-asic-chip-placement.md` would be better for the URL

2021-11-18 04:06 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +MakinaRocks의 COP(Combinatorial Optimization Problem) 팀에서는 이전 FPGA의 Placement & Routing에 강화학습을 적용하는 프로젝트에 이어 ASIC에서의 소자 배치를 자동화하는 프로젝트를 진행하고 있습니다.
FPGA 프로젝트 언급에서 해당 주제의 이전 블로그 포스팅 링크를 레퍼런싱하면 좋을 것 같습니다.

2021-11-18 04:08 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +MakinaRocks의 COP(Combinatorial Optimization Problem) 팀에서는 이전 FPGA의 Placement & Routing에 강화학습을 적용하는 프로젝트에 이어 ASIC에서의 소자 배치를 자동화하는 프로젝트를 진행하고 있습니다.
c.f.) Harvard Referencing
https://www.citethisforme.com/citation-generator/harvard

@WOOSHIK-M FYI

2021-11-18 04:10 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +ASIC은 이름대로 특정 용도에 맞게 주문제작한 반도체로 일반적인 반도체에 비해 낮은 소비전력 (power), 빠른 속도 (Performance), 낮은 면적 (Area)를 차지합니다. 이러한 metric을 통틀어 PPA라고 합니다.
PPA에 대해서는 추후 세부 기술시 좀 더 자세히 독자에게 알려주면 좋겠습니다.
(예시와 함께)

2021-11-18 04:11 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +ASIC이란 Application Specific Integrated Circuit 의 약자로 특정용도용 집적회로를 말합니다.
```suggestion
먼저 ASIC Chip Placement에 대해서 알아보겠습니다.
ASIC이란 Application Specific Integrated Circuit 의 약자로 특정용도용 집적회로를 말합니다.
```

2021-11-18 04:12 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +1.1 ASIC Chip Placement
ASIC Chip Placement가 상당히 많은 내용을 포괄하고 있는 것으로 보입니다.
- ASIC에 대해
- ASIC Chip Placement에 대해
- Metric
- Metric 개선이 어려운 이유

2021-11-18 04:15 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +Netlist에 포함된 소자는 상대적으로 크기가 큰 Macro와 크기가 작은 Standard Cell로 구분할 수 있습니다.
Deview 발표자료 해당 슬라이드의 메모에 Macro와 STD Cell의 세부설명이 기입되어 있습니다.
좀 더 세부적인 설명을 추가하는 것이 전반적인 글 이해에 더 도움이 될지 검토 부탁드립니다.

2021-11-18 04:15 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +즉, Physical Design 이전에서는 소자들의 특성과 연결관계를 정의하는 Netlist를 정의합니다.
Physical Design이 무엇인지?

2021-11-18 04:17 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +1.1 ASIC Chip Placement
Placement와 Floorplan을 별도의 과정으로 보는 경우가 많아보입니다.
저희의 문제는 Floorplan이기 때문에 용어선택에 좀 더 신경쓰면 좋곘네요.

2021-11-18 04:20 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +이러한 방식은 전문가의 역량에 따라 소요시간과 설계품질의 편차가 크게 나타납니다.
추후 세부내용 작성시 AS-IS에 대한 소요시간, 설계품질 문제에 대해 독자가 충분히 이해할 수 있도록 예시가 함께 주어지면 좋겠습니다.

2021-11-18 04:22 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +- Floor Planning: 비어있는 canvas에 Macro를 배치합니다.
```suggestion
- Floorplan: 비어있는 canvas에 Macro를 배치합니다.
```

2021-11-18 04:24 UTC, Curt-Park commented on _posts/2021-11-17-introduce_asic_chip_placement.md
> +저희는 문제를 점차 확장해가며 현재 122,406 개의 Cell을 배치하는 문제를 GNN, 강화학습을 사용하여 해결하였습니다.
```suggestion
저희는 문제를 점차 확장해가며 현재 122,406 개의 Cell을 배치하는 문제를 뉴럴넷, 강화학습을 사용하여 해결하였습니다.
```

2021-11-18 04:29 UTC, Curt-Park commented
노션에 기술하신 전반적인 목차에 대해 아웃라인기 기술되면 좋겠습니다.
(현재 목차중 일부 소단원만 기술)
https://www.notion.so/Tech-blog-cc2be1ff3fb242ecb93513e5973ff646

2021-11-19 01:58 UTC, Curt-Park commented
## Outline
1. 팀 소개 및 포스팅에 대한 목적 소개: 어떤 문제를 푸는 팀
2. ASIC Chip Placement에 대한 소개
  - ASIC 이 무엇인지?
  - Physical Design이 무엇인지? (Floorplan, Placement, Routing...)
  - 좋은 설계 - Metric (PPA?)
3. 문제에 대한 설명 (어려움): 복잡도
4. 문제의 의의: 개선했을 때의 기대효과, 현업자들의 니즈
5. 기존의 연구, 현재 트랜드: 강화학습의 타당성 (구글의 사례, 이전의 경민님 포스팅 레퍼런싱)
6. 우리가 다룬 문제
  - Toy 데이터부터 고복잡도 문제까지 문제의 스펙, 각 문제의 사용목적
7. 우리가 시도한 방법
  - 입력, 출력
  - ML 방법
  - 검증 방법 (ICC2)
8. 실험
  - Baselines
  - 실험 시나리오: 제약조건을 하나씩 풀어가는 방향으로
  - 실험 결과
9. 결론: 차후 도전 과제 (사용자에게 유용한 제품을 개발 / 기술 확장성)

2021-11-23 07:15 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +입력으로 사용하는 netlist의 크기는 ASICLand 디자인하우스의 현업자분들과 함께 다음과 같이 단계적으로 정의하고 있습니다.
왜 이렇게 단계적으정의했는가?
문제 정의의 당위성.

산업에서 유의미하다고 보는 복잡도의 문제 -> 100만개 소자의 Netlist -> 고복잡도 문제로 정의

2021-11-23 07:20 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +WNS는 Slack 중 최소 값을 의미하며 WNS는 0 이상이어야 합니다.
0보다 낮은거 -> 요구된 제약조건에 대한 Violation으로 볼 수 있음.

2021-11-23 07:21 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +학습 결과는 ICC2를 사용하여 검증합니다.
ICC2에 대한 설명을 앞서 할 필요 있음.

2021-11-23 07:21 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +이후 과정을 더 진행하지 않고 placement optimization까지만 진행한 이유는 이후 과정까지 진행하는데 시간이 오래 걸리기 때문입니다.
```suggestion
이후 과정을 더 진행하지 않고 placement optimization까지만 진행한 이유는 이후 과정까지 진행하는데 시간이 오래 걸리기 때문입니다.
```

2021-11-23 07:22 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +이후 ICC2 툴에서 제공하는 placement optimizatoin 과정까지 실행 후에 나오는 WNS, Frequency를 측정합니다.
placement optimization가 무엇인지?

2021-11-23 07:24 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +이후 과정을 더 진행하지 않고 placement optimization까지만 진행한 이유는 이후 과정까지 진행하는데 시간이 오래 걸리기 때문입니다.
사람이 작업하는 흐름을 따름.
실제 백엔드 엔지니어는 보통 Floorplan의 퀄리티를 검증할때 시간 등의 이유로 Placement Optimization까지 수행후 툴의 분석에 의한 성능을 측정 -> Violation이 안나는지 확인 -> 안나면 이후 작업 수행
-> Violation 나면 다시 처음부터

2021-11-23 07:26 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +Placement optimization까지 진행한 결과와 최종설계과정 까지 진행한 결과와 유사한 경향을 보인다는 디자인하우스의 조언을 따라 어느 단계에서 성능을 측정할지 결정하였습니다.
제거해도 될듯합니다.

2021-11-23 07:27 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +학습의 난이도를 점진적으로 높이며 실험 결과를 관측해보기 위해 다음의 세 가지 학습 시나리오를 정의했습니다. 뒤에 있는 시나리오일수록 학습 난이도가 높습니다.
하기에 what에 대한 설명만 있음. 각 시나리오에 대한 당위성 설명.
e.g. Single Cluster를 사용할 수 있는 근거

2021-11-23 07:27 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +학습의 난이도를 점진적으로 높이며 실험 결과를 관측해보기 위해 다음의 세 가지 학습 시나리오를 정의했습니다. 뒤에 있는 시나리오일수록 학습 난이도가 높습니다.
Cluster가 무엇인지?

2021-11-23 07:29 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +![image-20211122172910731](../assets/images/2021-11-17-introduce-asic-chip-placement/image-20211119102753962.png)
우리 프로젝트의 Technical overview에 맞는 새로운 그림 필요

2021-11-23 07:29 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +COP 팀이 사용한 모델은 다음과 같습니다.
COP?
아래 그림은 모델이라는 용어로 한정할 수 있는가?

2021-11-23 07:31 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +실험 결과 강화학습 모델은 전문가와 ICC2에서 제공하는 Auto Placement와 같거나 좋은 성능을 보여주었습니다.
- 결과가 더 좋다고 할 수 있나?
- Auto Placement가 무엇인지?

2021-11-23 07:32 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +그리고 다양한 Netlist에 대한 Generalization으로 학습에 대한 부담을 완화하고자 합니다.
Generalization <- 구체적
e.g. Generalization: 새로운 Netlist에 대해서 최소한의 추가 학습으로 설계를 도출

2021-11-23 07:33 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +그리고 다양한 Netlist에 대한 Generalization으로 학습에 대한 부담을 완화하고자 합니다.
현업자들의 니즈에 대한 언급도 있으면 좋을 것 같습니다.

2021-11-23 07:33 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +또한 Chip Placement 문제를 해결하면서 확보한 강화학습과 조합최적화 문제에 대한 기술을 활용해 다양한 조합최적화 문제에 확장하여 적용시킬 예정입니다.
다양한 문제의 예시

2021-11-23 07:34 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +categories: [test]
categories 논의 부탁드립니다.

2021-11-23 07:34 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +title: ASIC Chip Placement
Floorplan

2021-11-23 07:35 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +- 고복잡도 문제: 약 1,000,000개
무엇의 개수?

2021-11-23 07:40 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +이번 포스팅에서는 우리가 무엇을 했는지 요약하고, 다음 2부에서는 우리가 문제를 어떻게 해결했는지 자세하게 설명하겠습니다.
ASIC Chip Design의 도메인에 대한 설명 + COP에 대한 설명
<- 독자들에게 피로감을 주지 않을지 고민 필요 (데뷰에서는 COP 이야기를 뺐음)

2021-11-23 07:52 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +- Routing: 와이어 배치를 통해 Cell들을 물리적으로 연결합니다.
Floorplan은 수작업으로, 나머지는 Tool의 기능 사용
<- Floorplan은 왜 수작업으로 하는지?
<- 이로 인해 전반적 설계 품질이 Floorplan의 품질에 의존적

2021-11-25 05:52 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +MakinaRocks의 COP(Combinatorial Optimization Problem) 팀에서는 ASIC 반도체에서의 소자 배치를 자동화하는 Floorplan Automation 프로젝트를 진행하고 있습니다.
```suggestion
MakinaRocks의 COP(Combinatorial Optimization Problem) 팀에서는 ASIC(Application Specific Integrated Circuit) 반도체에서의 소자 배치를 자동화하는 Floorplan Automation 프로젝트를 진행하고 있습니다.
```

2021-11-25 05:52 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +그리고 다음 2부에서는 우리가 문제를 어떻게 해결했는지 자세하게 설명하겠습니다.
포스팅이 총 2부임을 언급

2021-11-25 05:55 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +ASIC은 이름대로 특정 용도에 맞게 주문제작한 반도체로 일반적인 반도체에 비해 낮은 소비전력 (power), 빠른 속도 (Performance), 낮은 면적 (Area)를 차지합니다. 이러한 metric을 통틀어 PPA라고 합니다.
일반적인 반도체가 지칭하는 대상이 분명하지 않음
```suggestion
ASIC은 이름대로 특정 용도에 맞게 주문제작한 반도체로 낮은 소비전력 (power), 빠른 속도 (Performance), 높은 집적도 (Area)를 보이는 것이 특징입니다. 
```

이러한 metric을 통틀어 PPA라고 합니다. <- 앞 뒤 문장과의 연결이 약간 부자연스러운 느낌을 줌

2021-11-25 05:57 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Electronic system-level design 단계에서는 ASIC의 기능 스펙을 정의합니다.
기능 스펙에 대한 예시 추가

2021-11-25 05:59 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Netlist는 각 소자가 어떤 소자로부터 전기신호를 받고 어떤 소자로 전기신호를 보내는지 나타냅니다.
Netlist에 대한 이해를 돕는 그림 추가

2021-11-25 06:01 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Standard Cell은 AND, OR, XOR 와 같은 Gate나 MUX, Flip Flop과 같은 기본적인 논리구조에 관련된 소자입니다.
STD Cell에 대한 정의 더블체크 필요

2021-11-25 06:06 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Physical Design 이후 여러가지 검증과정을 거쳐 ASIC Chip을 배포합니다.
이 문장을 통해 독자의 어떤 공감대를 만드려고 의도한 것이라면 좀 더 충분한 예시가 있어야 할 것 같습니다.
아니라면 문장을 빼도 무방해보입니다.

2021-11-25 06:11 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Physical Design 단계는 주어진 Netlist와 가이드라인에 맞게 비어있는 Chip canvas 위에 소자들을 배치하고 와이어를 연결합니다.
- 가이드라인이 무엇인지? (간단 예시)
- 영어 표기 방법 통일

2021-11-25 06:11 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Physical Deisgn에서 Macro를 먼저 배치하는 이유는 canvas 위에서 많은 영역을 차지하고, Maco의 배치에 대한 가이드라인이 있기 때문입니다.
```suggestion
Physical Deisgn에서 Macro를 먼저 배치하는 이유는 canvas 위에서 많은 영역을 차지하고, Macro의 배치에 대한 가이드라인이 있기 때문입니다.
```
가이드라인에 대한 사전 설명 필요

2021-11-25 06:15 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +EDA는 컴퓨터를 활용해 Chip design에 도움을 주는 프로그램으로 ICC2, Cadence 등이 있습니다.
Cadence는 회사 이름입니다.

2021-11-25 06:16 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +저희는 ICC2를 사용했습니다.
이 문장이 있으면 ICC2를 사용하게 된 근거도 간략히 기술되어야 함.

2021-11-25 06:17 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Floorplan은 아직 충분한 성능과 속도를 보장하거나 툴이 없기 때문에 엔지니어들이 수작업으로 진행합니다.
```suggestion
Floorplan은 아직 충분한 성능을 보장하는 툴이 없기 때문에 주로 엔지니어들이 수작업으로 작업을 진행합니다.
```

2021-11-25 06:19 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +따라서 저희 COP 팀은 충분한 성능과 속도를 보장하는 Floorplan 자동화 툴을 개발하여 엔지니어들의 니즈를 채우고자 합니다.
```suggestion
따라서 저희 COP 팀은 충분한 성능을 보장하는 Floorplan 기술을 확보하여 디자이너들의 불편을 해소하고자 합니다.
```

2021-11-25 06:20 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +따라서 저희 COP 팀은 충분한 성능과 속도를 보장하는 Floorplan 자동화 툴을 개발하여 엔지니어들의 니즈를 채우고자 합니다.
`반도체 설계 전문가`

2021-11-25 06:21 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +
서론: 좋은 Floorplan? 우선 좋은 설계가 무엇인지 판단을 도와주는 Metric을 정의해야 함

2021-11-25 06:22 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Wire 길이는 좋은 PPA를 나타내는 하나의 척도입니다.
Wire라는 표현이 여기서 처음 등장 <- 설명 필요

2021-11-25 06:24 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +따라서 소자들을 가까이 배치했지만 Wire를 배치할 때 Routing Resource를 초과한다면 소자들을 최단거리로 연결하는 것이 아니라 우회해서 연결해야 합니다.
Routing Resource가 캔버스 전체에 대해 주어지는 것으로 보일 수 있음.
-> 68 line에 대해 오해가 발생할 소지가 있음

2021-11-25 06:25 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +이렇게 Routing Resource를 초과하는 것을 Congestion이라 하며, Congestion이 발생하면 Wire 길이가 길어지게 됩니다.
Congestion의 정의에 대한 오해가 생길 수 있음
Congestion = demand / supply

2021-11-25 06:26 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +
그림 추가

2021-11-25 06:27 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +따라서 좋은 Floorplan은 소자들을 충분히 가까우면서 Congestion이 발생하지 않게하는 소자들의 '적절한 위치'를 찾는 것입니다.
```suggestion
따라서 좋은 Floorplan은 소자들을 충분히 가까우면서 Congestion이 발생하지 않게하는  '적절한 위치'를 찾는 것입니다.
```

2021-11-25 06:28 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +이러한 소자들의 '적절한 위치'를 찾는 작업은 어려운 작업입니다.
```suggestion
소자들의 '적절한 위치'를 찾는 작업은 어려운 작업입니다.
```

2021-11-25 06:29 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +엔지니어는 수십~수백 개의 소자들의 연결관계를 고려해서 각 소자들의 '적절한 위치를 찾아야 합니다.
> 수십~수백 개의 소자들의 연결관계를
스케일이 다소 작아 보입니다.

2021-11-25 06:33 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +따라서 Floorplan 자동화는 현재 반도체 업계에 수요가 있는 기술입니다.
팹리스, 디자인하우스 같은 용어 없이 의의를 설명할 수 있으면 좋겠습니다.

2021-11-25 06:35 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +하지만 이런 연구들은 1) 시간이 매우 오래 걸리거나 2) 대규모 소자배치에 적합하지 않거나 3) 소자 배치 결과가 전문가에 비해 성능이 낮다는 문제가 있습니다.
1. 간략하게나마 각 연구 주제들을 설명하거나 (한계점)
2. 기존 연구의 한계점을 2.2의 서두에 쓰거나.

2021-11-25 06:36 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +## 2.2 강화학습의 타당성
```suggestion
## 2.2 강화학습을 이용한 Floorplan / 강화학습
```

2021-11-25 06:37 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +최근에는 이러한 문제를 해결하고자 하는 연구들이 지속적으로 발표되고 있습니다.
> 이러한 문제를

문제를 구체적으로 지칭하는 것이 더 좋을 것 같습니다.

2021-11-25 06:39 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +하지만 이런 연구들은 1) 시간이 매우 오래 걸리거나 2) 대규모 소자배치에 적합하지 않거나 3) 소자 배치 결과가 전문가에 비해 성능이 낮다는 문제가 있습니다.
2번이 1,3과 Redundant

2021-11-25 06:47 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +강화학습은 머신러닝의 방법 중 하나로 성능 평가 측정치로 결과물에 대한 피드백을 통해 성능을 최대화하는 방향으로 학습하는 방법입니다. 강화학습은 배치 성능을 측정하는 방법은 존재하지만 최적의 배치를 알지 못한다는 점에서 Floorplan에 적합한 머신러닝 기법입니다.
앞선 클래식 방식들과 비교할때 Metric의 사용에 의해 강화학습이 이 문제에서 더 적합하다는 오해를 만들 수 있어보임
(의도: 강화학습도 클래식 방법들과 마찬가지로 이 문제에서 하나의 옵션으로 고려될 수 있다.)

2021-11-25 06:52 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +하지만 이런 연구들은 1) 시간이 매우 오래 걸리거나 2) 대규모 소자배치에 적합하지 않거나 3) 소자 배치 결과가 전문가에 비해 성능이 낮다는 문제가 있습니다.
2.2에서 강화학습의 일반화를 강화학습의 타당성으로 언급하므로, 클래식 방식의 한계점도 일반화와 연결지어서 이야기하는 것이 자연스러워 보입니다.

2021-11-25 06:54 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +성능 평가 metric은 PPA 중에 Performance를 사용합니다.
power와 area는 요구조건에 따라 고정하고 시작함. 그래서 performance만 보는 것으로.

2021-11-25 06:56 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-2.md
> +성능 평가 metric은 PPA 중에 Performance를 사용합니다.
PPA 중 퍼포먼스를 이용하는 이유

2021-12-01 06:00 UTC, yu2jeong commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +WNS는 Slack 중 최솟값을 의미합니다.
글 설명에는 WNS가 Slack의 최솟값이라고 설명되어있고 수식에서는 max로 되어있는데 제가 놓친 부분이 있을까요?

2021-12-01 08:21 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +그리고 다음 2부에서는 COP 팀이 문제를 어떻게 해결했는지 자세하게 설명하겠습니다.
우식님의 포스팅 링크는 이 부분에서 보여주시나요?

2021-12-01 08:23 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +ASIC은 요구되는 주문 사항을 만족시키기 위해 낮은 소비전력 (power), 빠른 속도 (Performance), 높은 집적도 (Area)를 보입니다.
좋은 PPA는 ASIC이 항상 보이는 상태라기 보다는 목적에 가까우므로 아래와 같이 수정하면 어떨까요?
```suggestion
ASIC은 요구되는 주문 사항을 만족시키기 위해 낮은 소비전력 (power), 빠른 속도 (Performance), 높은 집적도 (Area)를 목표로 합니다.
```

2021-12-01 08:24 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +</figure>
그림이 안보입니다.
<img width="791" alt="스크린샷 2021-12-01 오후 5 23 55" src="https://user-images.githubusercontent.com/14961526/144198182-b1e2457b-2f2e-48e5-8732-97c018b76f47.png">

2021-12-01 08:26 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +</figure>
그림이 안나옵니다.
<img width="883" alt="스크린샷 2021-12-01 오후 5 26 03" src="https://user-images.githubusercontent.com/14961526/144198503-aebff831-83e1-427f-a9b7-dbe8bcb75acc.png">

2021-12-01 08:30 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +EDA는 컴퓨터를 활용해 Chip design에 도움을 주는 프로그램입니다.
영문표현 통일
```suggestion
EDA는 컴퓨터를 활용해 Chip Design에 도움을 주는 프로그램입니다.
```

2021-12-01 08:33 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +하지만 Floorplan은 반도체 설계 전문가의 역량에 따라 소요 시간과 설계 품질의 편차가 크게 나타납니다.
- 엔지니어, 전문가 -> 엔지니어로 통일
- 두 문장이 인과관계를 갖으므로 '하지만' 제거
```suggestion
그동안 Floorplan은 엔지니어의 경험과 감에 의존했으므로 엔지니어의 역량에 따라 소요 시간과 설계 품질의 편차가 크게 나타납니다.
```

2021-12-01 08:34 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +저희는 반도체 설계 업계에 종사하는 Logic Design 개발자와 Physical Design 개발자에게 Floorplan 자동화에 대해 어떻게 생각하는지 여쭈어보았습니다.
Designer가 아니라 보통 Design 개발자라고 불리나요?

2021-12-01 08:35 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +또한 소자나 Chip canvas에 변동이 생기면 다시 적용하여 배치를 찾아야 합니다.
무엇을 적용하나요?

2021-12-01 08:36 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +그리고 그중 하나는 좋은 배치를 학습하는 것입니다.
좋은 배치예시를 뉴럴넷에 학습한다는 것인가요?

2021-12-01 08:40 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +$$\text{WNS} = \max_{v\in node}(\text{Required Arrival Time}(v) - \text{Actual Arrival Time}(v))$$
min 아닐까요?
```suggestion
$$\text{WNS} = \min_{v\in node}(\text{Required Arrival Time}(v) - \text{Actual Arrival Time}(v))$$
```

2021-12-01 08:41 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +</figure>
그림이 안보이네요.

2021-12-01 08:41 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +먼저 Netlist에 있는 소자 간의 연결 관계 정보와 Canvas 위에 배치된 cell 들의 배치 정보를 뉴럴 네트워크를 활용해 embedding 합니다.
```suggestion
먼저 Netlist에 있는 소자 간의 연결 관계 정보와 Canvas 위에 배치된 Cell 들의 배치 정보를 뉴럴 네트워크를 활용해 embedding 합니다.
```

2021-12-01 08:41 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +강화학습 Agent는 embedding 된 값을 기반으로 다음 Cell을 어디에 배치할지 결정합니다.
```suggestion
강화학습 Agent는 Embedding 된 값을 기반으로 다음 Cell을 어디에 배치할지 결정합니다.
```

2021-12-01 08:42 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +학습이 끝나면 가장 높은 Reward를 갖는 macro 배치 정보를 출력합니다.
```suggestion
학습이 끝나면 가장 높은 Reward를 갖는 Macro 배치 정보를 출력합니다.
```

2021-12-01 08:42 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +- Single Cluster + bounding box: 첫 번째 시나리오는 Standard Cell을 하나의 Cluster로 가운데에 배치하고, Macro는 입출력 포트를 제외한 가장자리 영역에만 배치할 수 있도록 하는 경우입니다. 수작업의 반도체 설계에서 Macro를 주로 가장자리에 배치한다는 것과 Standard Cell이 주로 가운데에 배치된다는
```suggestion
- Single Cluster + Bounding Box: 첫 번째 시나리오는 Standard Cell을 하나의 Cluster로 가운데에 배치하고, Macro는 입출력 포트를 제외한 가장자리 영역에만 배치할 수 있도록 하는 경우입니다. 수작업의 반도체 설계에서 Macro를 주로 가장자리에 배치한다는 것과 Standard Cell이 주로 가운데에 배치된다는 것에 착안하여 정의했습니다.
```

2021-12-02 05:28 UTC, Curt-Park commented
슬슬 맞춤법 검사기도 한번 돌려주세요.
https://speller.cs.pusan.ac.kr/

2021-12-03 03:44 UTC, CUN-bjy requested changes
![Screenshot from 2021-12-03 11-56-22](https://user-images.githubusercontent.com/26274945/144541670-a516c3eb-d082-4f1b-8158-e44af40142a6.png)
아래문장과 내용적으로 겹치는 느낌이 있는 것 같습니다.
총 2부로 이루어져있으며 1부인 이번 포스팅에서는 ~, 2부는 ~ 로 소개할 예정입니다.
이렇게 전개해보면 어떨까요?

2021-12-03 03:47 UTC, CUN-bjy requested changes
![Screenshot from 2021-12-03 12-44-39](https://user-images.githubusercontent.com/26274945/144541798-1100716a-29b4-4f84-8438-349d7363d9c6.png)

문장이 어색하게 느껴집니다.
`단계에서` -> `단계에서는`, 
`Netlist에서 Net들의 집합입니다` -> `Netlist는 Net의 집합입니다`
이렇게 바꾸면 본래의 의미가 잘 전달될 것 같습니다!

2021-12-03 03:57 UTC, CUN-bjy requested changes
![Screenshot from 2021-12-03 12-48-04](https://user-images.githubusercontent.com/26274945/144542185-ec2d9071-cec7-4e61-b129-2ee9c9e1619e.png)

<4페이지>
1. PPA의 약자가 무엇인지 명시되어있지 않은 것 같습니다.
2. Chip Canvas의 같은 위치(?)에 배치한다는 개념이 잘 와닿지 않았습니다. 
  - Violation이 일어나는 상황에 대한 개념을 위해 보다 명확한 표현이 필요해보입니다. 그림으로부터 추론해보자면 wire crossing이 일어나면 안된다? 라는 개념이라고 생각되었습니다.(해당개념을 잘 모르는 입장이니 이해 부탁드립니다.) `같은 위치`라는 개념에 대해 설명해주시면 좋을 것 같습니다.
  - 읽는 중 자연스럽게 아래 그림을 확인할 수 있게 글에서 아래 그림을 함께 보라고 언급해주시면 어느 타이밍에 그림을 함께 참고하면 되는지 도움이 될 것 같습니다.

2021-12-03 04:05 UTC, Curt-Park commented
<img width="1066" alt="스크린샷 2021-12-03 오후 1 05 38" src="https://user-images.githubusercontent.com/14961526/144543532-c816838c-d444-4365-b66b-9fb3551384bc.png">
Site generation 과정에서 conflict이 발생합니다.

2021-12-03 04:14 UTC, Curt-Park commented
`_config.yml`에 작성자 정보를 추가해주세요.

2021-12-03 04:20 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +이번 포스팅에서는 산업에서 Floorplan Automation이 현업자들에게 어떠한 도움을 주는지, 그리고 COP 팀이 무엇을 했는지 요약하겠습니다.
바로 앞 문장과 내용이 중복됩니다.
`총 2부에 걸쳐 Floorplan Automation이 현업자들에게 어떠한 도움을 주는지, 그리고 우리가 어떻게 문제를 해결하고 있는지 이야기하고자 합니다.`

2021-12-03 04:21 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +ASIC은 요구되는 주문 사항을 만족시키기 위해 낮은 소비전력 (power), 빠른 속도 (Performance), 높은 집적도 (Area)를 목표로 합니다.
```suggestion
ASIC은 요구되는 주문 사항을 만족시키기 위해 낮은 소비전력 (Power), 빠른 속도 (Performance), 높은 집적도 (Area)를 목표로 합니다.
```

2021-12-03 04:21 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +System-level Design 단계에서는 ASIC이 제공해야 할 기능, power, timing 그리고 area와 같은 ASIC 스펙 등을 정의합니다.
```suggestion
System-level Design 단계에서는 ASIC이 제공해야 할 기능, Power, Timing 그리고 Area와 같은 ASIC 스펙 등을 정의합니다.
```

2021-12-03 04:23 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +마지막으로 Physical Design 단계에서는 Netlist를 사용해 실질적인 소자 배치합니다.
```suggestion
마지막으로 Physical Design 단계에서는 Netlist를 사용해 실질적으로 소자를 배치합니다.
```

2021-12-03 04:24 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +국내에서 많이 사용되는 프로그램으로는 ICC2가 있습니다.
More Information can be provided

```suggestion
국내에서 많이 사용되는 프로그램으로는 [Synopsys](https://www.synopsys.com/)사의 ICC2가 있습니다.
```

2021-12-03 04:25 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +하지만 Chip Canvas의 같은 위치에 Wire를 배치할 수 있는 개수(Routing Resource)가 정해져 있습니다.
`개수` 보다 `자원`은 어떨까요?

2021-12-03 04:28 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Floorplan은 반도체 설계 전문가의 역량에 따라 소요 시간과 설계 품질의 편차가 크게 나타납니다.
두 문장이 인과관계를 갖고 있어서 적절히 연결성을 주면 좋을 것 같습니다.
e.g.
```suggestion
Floorplan은 주로 반도체 설계 전문가의 경험과 감에 의존하기 때문에 전문가의 역량에 따라 소요 시간과 설계 품질의 편차가 크게 나타납니다.
```

2021-12-03 05:05 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +또한 소자나 Chip canvas에 변동이 생기면 다시 메타휴리스틱을 적용하여 배치를 찾아야 합니다.
```suggestion
또한 소자나 Chip Canvas에 변동이 생기면 다시 메타휴리스틱을 적용하여 배치를 찾아야 합니다.
```

2021-12-03 05:08 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +최근에는 새로운 방식으로 Floorplan 문제에 접근하는 연구도 제안되고 있습니다.
`연구가 제안되다.` <- 보통 사용하는 표현인가요?
e.f.
`연구 방향이 제안되다`
`연구 결과가 공개되다`

2021-12-03 05:09 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +강화학습은 머신러닝의 방법의 하나로 성능 평가 측정치로 결과물에 대한 피드백을 통해 성능을 최대화하는 방향으로 학습하는 방법입니다.
```suggestion
강화학습은 머신러닝 방법의 하나로 성능 평가 측정치로 결과물에 대한 피드백을 통해 성능을 최대화하는 방향으로 학습하는 방법입니다.
```

2021-12-03 05:14 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +최근에는 새로운 방식으로 Floorplan 문제에 접근하는 연구도 제안되고 있습니다.
뒷 문단이 `이에 따라 강화학습으로 Floorplan 문제를 해결하는 연구들이 제안되고 있습니다.` 이렇게 끝나므로 서두에서는 표현을 우회적으로 하여 중복을 줄이는 것도 괜찮을 듯 합니다.

`최근에는 좋은 배치를 출력하도록 뉴럴네트워크를 '학습'시키는 방법으로 Floorplan 문제를 해결하려는 움직임이 보여지고 있습니다.`

2021-12-03 05:15 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +성능 평가 metric은 PPA 중에 Performance를 사용합니다.
```suggestion
성능 평가 Metric은 PPA 중에 Performance를 사용합니다.
```

2021-12-03 05:15 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +Performance는 Worst Negative Slack (WNS), Frequency와 같은 timing metric으로 측정합니다.
```suggestion
Performance는 Worst Negative Slack (WNS), Frequency와 같은 Timing Metric으로 측정합니다.
```

2021-12-03 05:17 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +디자인하우스의 반도체 설계 전문가의 Floorplan 진행 상황을 관찰할 때 Standard Cell이 Canvas 중앙에 가도록 Macro를 되도록 Canvas의 외곽 쪽에 배치한다는 것을 확인할 수 있었습니다.
이유도 짧막하게 덧붙이면 어떨까요?

e.g. Standard Cell들 간의 연결성이 강하기 때문에...

2021-12-03 05:18 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +또한 Floorplan 문제를 해결하면서 확보한 강화학습과 조합 최적화 문제에 관한 기술을 활용해 물류 거점 최적화, 생산설비 최적화 등의 조합 햐최적화 문제에 확장하여 적용할 예정입니다.
```suggestion
또한 Floorplan 문제를 해결하면서 확보한 강화학습과 조합 최적화 문제에 관한 기술을 활용해 물류 거점 최적화, 생산설비 최적화 등의 조합 최적화 문제에 확장하여 적용할 예정입니다.
```

2021-12-03 05:19 UTC, Curt-Park commented on _posts/2021-11-17-introduce-asic-chip-placement-part-1.md
> +다음 포스팅에서는 COP 팀이 Floorplan 자동화 문제를 어떻게 해결하였는지 구체적인 내용을 말씀드리도록 하겠습니다.
- 이 문장 아래에 우식님의 포스팅 링크가 있으면 어떨까요?
- Deview 영상 링크도 달아두면 어떨까 싶습니다.

2021-12-03 05:21 UTC, Curt-Park commented
<img width="756" alt="스크린샷 2021-12-03 오후 2 21 24" src="https://user-images.githubusercontent.com/14961526/144549848-dcb422d8-4e9a-4939-b1a2-467eb9c2a398.png">
썸네일이 유효하지 않습니다.

2021-12-06 01:21 UTC, CUN-bjy approved these changes

2021-12-06 02:21 UTC, Curt-Park commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +그리고 [다음 2부](https://makinarocks.github.io/ASIC-Floorplan-Automation-Part-2)에서는 COP 팀이 문제를 어떻게 해결했는지 자세하게 설명하겠습니다.
서론이 먼저 나오면 어떨까 합니다.
(Related to가 home에서 썸네일과 함께 노출됨)

<img width="1157" alt="스크린샷 2021-12-06 오전 11 20 58" src="https://user-images.githubusercontent.com/14961526/144776953-9ae7d2fd-a170-49bf-80db-6b9015d5ba4c.png">

```suggestion
MakinaRocks의 COP(Combinatorial Optimization Problem) 팀에서는 주문형 반도체(Application Specific Integrated Circuit, ASIC)에서의 소자 배치를 자동화하는 Floorplan Automation 프로젝트를 진행하고 있습니다.
총 2부에 걸쳐 저희가 진행한 Floorplan Automation 프로젝트에 대해서 소개하고자 합니다.
이번 포스팅에서는 산업에서 Floorplan Automation이 현업자들에게 어떠한 도움을 주는지, 그리고 COP 팀이 현재 어떤 결과를 내었는지 요약하겠습니다.
그리고 [다음 2부](https://makinarocks.github.io/ASIC-Floorplan-Automation-Part-2)에서는 COP 팀이 문제를 어떻게 해결했는지 자세하게 설명하겠습니다.

# Related to
* [강화학습, 산업의 난제에 도전하다! - ASIC 반도체 설계 (Floorplan) 자동화 (Naver Deview 21 발표 영상)](https://tv.naver.com/v/23650123)
* [ASIC-Chip-Placement 2부](https://makinarocks.github.io/ASIC-Floorplan-Automation-Part-2)
```

2021-12-06 02:24 UTC, Curt-Park approved these changes

2021-12-06 04:32 UTC, merged

2021-12-06 05:48 UTC, taeholeee reviewed
전체적으로 아웃라인이 좋아보입니다.
그러나 각 문장별로 코멘트를 달아드렸듯이, 요약문에서 미리 언급됐으면 하는 내용들이 있었습니다.
요약문 자체도 중복된 문장으로 구성되고 내용이 빈약하기 때문에 제 코멘트를 반영하여 요약문을 보충하면 좋겠습니다.
또 대부분 영문이 대문자를 각 단어 시작으로 사용하는데 의도된 것인지 적절한 것인지에대해 궁금합니다.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +이번 포스팅에서는 산업에서 Floorplan Automation이 현업자들에게 어떠한 도움을 주는지, 그리고 COP 팀이 현재 어떤 결과를 내었는지 요약하겠습니다.
이 부분 이전 커밋에서 커멘트 달았습니다.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +ASIC이란 Application Specific Integrated Circuit의 약자로 가전, 휴대폰, 자동차 등 특정한 제품을 위해 주문 제작한 반도체입니다.
일반적으로 반도체에 ASIC이 아닌 반도체는 어떤것이 있는지 드러나면 독자에게 도움이 될것 같습니다.
"CPU와 같은 general purpose ...나 RAM곽 같은 메모리 반도체 ... 와 달리.. " 와 같이 간단한 구절을 추가하면 더 친절할거 같네요.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +ASIC 설계는 아래의 그림과 같이 진행됩니다.
블로그 레이아웃이 한 컬럼으로 세로로 긴 형태여서, 세로로 긴 이미지가 가독성을 해칠까 염려되네요, 그림을 가로로 다시 그리는건 불가능한가요?

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +Netlist에서 Net의 집합입니다.
주어가 없습니다. 문장의 호응이 안맞아서 뭐가 Net의 집합이라는건지 알 수가 없습니다.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +ASIC 설계는 아래의 그림과 같이 진행됩니다.
단순히 아래 그림과 같이 진행된다고 적기보다, System-level Design, Logic Design, Physical Design으로 나누어진다는걸 미리 글로 언급해주는게 필요해보입니다. 글을 읽어가면서 이 섹션에서 무엇을 설명하려고 했는지 뒤늦게 알 수 있었습니다.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +마지막으로 Physical Design 단계에서는 Netlist를 사용해 실질적으로 소자 배치합니다.
이 부분이 왜 새로운 서브섹션 1.3으로 설명되어야하는지 미리 적어주면 좋겠습니다.
뒷 내용을 다 읽어보면 결국 Floorplan에대해 설명하기 위한것인데, 이를 미리 알수 없었습니다.
처음 요약문에서 Floorplan이란 용어가 등장했는데, 이 부분에 대한 설명을 위해 섹션 1을 찬찬히 high-level에서 low-level로 설명될 것이란 언급이 요약문에 보충되면 좋을것 같습니다.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +저희 COP 팀은 충분한 성능을 보장하는 Floorplan 자동화 기술을 확보하여 반도체 설계 전문가들의 불편을 해소하고자 합니다.
어떤점이 전문가가 불편해하는 부분인가요?
수작업으로 하는게 불편한 점이라면 이 부분을 명확히 해줘야할것 같습니다.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +Wire 길이는 좋은 PPA를 나타내는 하나의 척도입니다.
Wire길이가 PPA의 척도가 될 수 있나요? PPA가 척도이고 Wire길이는 그 척도에 영향을줄 수 있는 팩터 아닐까싶습니다.
"일반적으로 Wire길이가 짧아지면 PPA가 좋아집니다" 같은 확실한 표현이 어떨까요?

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +강화학습은 머신러닝 방법의 하나로 결과물에 대해 성능 평가 측정치로 피드백을 주어 성능을 최대화하는 방향으로 학습하는 방법입니다.
"결과물에 대해 성능 평가 측정치로 피드백을 주어 성능을 최대화하는 방향으로 학습"라는 설명이 강화학습이 아닌 다른 머신러닝 방법에도 일반적으로 해당하는 내용이 아닐까요?
설명의 의도는 이해하지만 decision process의 결과물에 대한 성능 평가라던가, 조금더 구체적으로 다른 머신러닝과 다른 강화학습만의 특징을 설명해주면 좋을것 같습니다.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +강화학습은 머신러닝 방법의 하나로 결과물에 대해 성능 평가 측정치로 피드백을 주어 성능을 최대화하는 방향으로 학습하는 방법입니다.
특히 이어지는 문장에서 최적의 배치를 알지못하기 때문에 강화학습에 적합하다고 하셨는데,
이 문장과 홍응 맞도록 이부분의 특징을 드러내는 정의로 다시 쓰시길 권해드립니다.

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +- Toy Example: 소자 237개
독자들이 아래 구체적인 숫자의 기준을 어떻게 정했는지 궁금해할거 같습니다.
이 부분에대해 설명이 가능할까요?

2021-12-06 05:48 UTC, taeholeee commented on _posts/2021-12-03-ASIC-Floorplan-Automation-Part-1.md
> +Clustering 이후 Netlist에 있는 소자 간의 연결 관계 정보와 Canvas 위에 배치된 소자들의 배치 정보를 뉴럴 네트워크를 활용해 Embedding 합니다.
어디에 embedding하겠다는건지 목적어가 빠져있습니다.
문맥상 embedding을 "feature learning"혹은 "information을 학습" 하고자하는 의미로 사용하신거 같습니다.
이 경우라면 의도대로 명확히 표현하시거나 embedding을 쓰고싶으시다면 무엇을 어디에 embedding했는지 정확한 표현을 쓰면 좋겠습니다.